### ISSUE TITLE
Plexmediaserver fails to start - active (exited)

### ISSUE THREAD

**Issue by Sashboy** [uglymagoo/plexmediaserver-installer#10]
After installation following instructions on dev2day, when querying the service status this is the output:
```
● plexmediaserver.service – LSB: Plex Media Server
Loaded: loaded (/etc/init.d/plexmediaserver)
Active: active (exited) since Tue 2017-03-07 21:37:46 EST; 9min ago
Process: 360 ExecStart=/etc/init.d/plexmediaserver start (code=exited, status=0/SUCCESS)
Mar 07 21:37:41 Plex-Server systemd[1]: Starting LSB: Plex Media Server…
Mar 07 21:37:43 Plex-Server su[399]: Successful su for plex by root
Mar 07 21:37:43 Plex-Server su[399]: + ??? root:plex
Mar 07 21:37:43 Plex-Server su[399]: pam_unix(su:session): session opened f…0)
Mar 07 21:37:46 Plex-Server plexmediaserver[360]: Starting Plex Media Server:…
Mar 07 21:37:46 Plex-Server systemd[1]: Started LSB: Plex Media Server.
Hint: Some lines were ellipsized, use -l to show in full.
```
System: Raspberry Pi 2

After googling, i've seen this about 3 times in various forums without a resolution.

**Comment by uglymagoo** [comment]
@Sashboy  That's OK. The service should be up and running. Are you unable to access Plex via https://local.ip:32400/web ?

**Comment by Sashboy** [comment]
@uglymagoo Unable to connect. "Connection refused"

**Comment by uglymagoo** [comment]
@Sashboy Please make sure you really have a Raspberry Pi 2 and not a Raspberry Pi 1 model B. Please post the result of  `uname -a`.

**Comment by Sashboy** [comment]
I got rid of my RPi 1 a couple of years ago. Definitely RPi2.
Just at work atm. Even on the pi through chromium doing localhost:32400/web says connection refused.

**Comment by uglymagoo** [comment]
OK. Please switch over to our [unofficial support thread in the Plex forum](http://forums.plex.tv/discussion/comment/1390379#latest). We will discuss this there because it's not an issue with the plexmediaserver-installer.

**Comment by ghost** [comment]
I have the same problem with the server:
ARM64-2GB
ARMv8

from scaleway.com: https://www.scaleway.com/pricing/

```
$ systemctl status plexmediaserver
● plexmediaserver.service - LSB: Plex Media Server
   Loaded: loaded (/etc/init.d/plexmediaserver; bad; vendor preset: enabled)
   Active: active (exited) since Sat 2017-05-13 03:54:20 UTC; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1832 ExecStop=/etc/init.d/plexmediaserver stop (code=exited, status=0/SUCCESS)
  Process: 1840 ExecStart=/etc/init.d/plexmediaserver start (code=exited, status=0/SUCCESS)

May 13 03:54:19 plex-media-server systemd[1]: Starting LSB: Plex Media Server...
May 13 03:54:19 plex-media-server su[1847]: Successful su for plex by root
May 13 03:54:19 plex-media-server su[1847]: + ??? root:plex
May 13 03:54:19 plex-media-server su[1847]: pam_unix(su:session): session opened for user plex by (uid=0)
May 13 03:54:20 plex-media-server plexmediaserver[1840]: Starting Plex Media Server: done
May 13 03:54:20 plex-media-server systemd[1]: Started LSB: Plex Media Server.
```

```
$ uname -a
Linux plex-media-server 4.9.23-std-1 #1 SMP Mon Apr 24 13:18:14 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

```
$ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 200.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
CPU implementer : 0x43
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0x0a1
CPU revision    : 1

processor       : 1
BogoMIPS        : 200.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
CPU implementer : 0x43
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0x0a1
CPU revision    : 1
```

**Comment by uglymagoo** [comment]
Your problem is completely unrelated to this issue, as the user had an unsupported RPi Zero. Please follow the same advice (See my previous post on the top) and post in the our plex.tv support thread. Please also provide logs.

**Comment by uglymagoo** [comment]
Btw: did you use a ssh tunnel to access plex port 32400 as described in the Installation guide? https://support.plex.tv/hc/en-us/articles/200288586-Installation

**Comment by ghost** [comment]
Thank you for your answer.
The problem is that Plex does not start after enabling and starting it with the commands:
```
sudo systemctl enable plexmediaserver
sudo systemctl start plexmediaserver
```

The command: `ps aux | grep -i plex` returns nothing.

It's not possible to provide any Plex internal log since it is not running, the only log I can provide is the output of the journal after trying to start plexmediaserver, and this log was already provided above:
```
$ systemctl status plexmediaserver
● plexmediaserver.service - LSB: Plex Media Server
   Loaded: loaded (/etc/init.d/plexmediaserver; bad; vendor preset: enabled)
   Active: active (exited) since Sat 2017-05-13 03:54:20 UTC; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1832 ExecStop=/etc/init.d/plexmediaserver stop (code=exited, status=0/SUCCESS)
  Process: 1840 ExecStart=/etc/init.d/plexmediaserver start (code=exited, status=0/SUCCESS)

May 13 03:54:19 plex-media-server systemd[1]: Starting LSB: Plex Media Server...
May 13 03:54:19 plex-media-server su[1847]: Successful su for plex by root
May 13 03:54:19 plex-media-server su[1847]: + ??? root:plex
May 13 03:54:19 plex-media-server su[1847]: pam_unix(su:session): session opened for user plex by (uid=0)
May 13 03:54:20 plex-media-server plexmediaserver[1840]: Starting Plex Media Server: done
May 13 03:54:20 plex-media-server systemd[1]: Started LSB: Plex Media Server.
```
There is no point in doing a ssh tunnel since Plex is not running, normally I run the command:
`ssh user@IP -L lport:localhost:32400` to enable the tunnel but since Plex is not running I didn't do it.

**Comment by uglymagoo** [comment]
Do you know how to set LD_LIBRARY_PATH? Can you please try to start the "Plex Media Server" manually? I am interested in the error message. I assume it is either a segmentation fault or illegal instruction. 

In the first case, I assume it is the same error like in the closed AMD armv8 issue and can be fixed by using the Synology build.

**Comment by ghost** [comment]
I deleted the server instance so I can't help you with this, sorry.
