### ISSUE TITLE
The certificate of ‘dev2day.de’ is not trusted.

### ISSUE THREAD

**Issue by asliwinski** [uglymagoo/plexmediaserver-installer#12]
wget -O - https://dev2day.de/pms/dev2day-pms.gpg.key | apt-key add -
--2017-04-06 00:27:54--  https://dev2day.de/pms/dev2day-pms.gpg.key
Resolving dev2day.de (dev2day.de)... 144.76.172.47, 2a01:4f8:200:502e::2
Connecting to dev2day.de (dev2day.de)|144.76.172.47|:443... connected.
ERROR: The certificate of ‘dev2day.de’ is not trusted.
ERROR: The certificate of ‘dev2day.de’ is not yet activated.
The certificate has not yet been activated
gpg: no valid OpenPGP data found.

**Comment by uglymagoo** [comment]
1. Just set the correct date and time in your Linux system. "is not yet activated" means your Linux system thinks the activation date of my certificate has not passed ;) 
2. Not an issue of the code in this repo
