### ISSUE TITLE
debian stretch builds

### ISSUE THREAD

**Issue by TheOneRing** [uglymagoo/plexmediaserver-installer#13]
I know its too early to try to update my pi to stretch but I'd like to.
The only thing holding me back are the missing plex builds

**Comment by jaymoulin** [comment]
Did you consider Docker? https://hub.docker.com/r/jaymoulin/rpi-plex/

**Comment by uglymagoo** [comment]
@TheOneRing Does my current package not work on Debian 9.x? If so, please post more details about the problem. Ubuntu 16.10 does not have any problems, so I am surprised there is an issue with Debian 9. Just use my jessie repo and you should be fine.

**Comment by TheOneRing** [comment]
I'll backup everything of importance and try it ^^

**Comment by TheOneRing** [comment]
Your absolutely right, works like a charm
