### ISSUE TITLE
Package error on dev2day instructions

### ISSUE THREAD

**Issue by opentrail** [uglymagoo/plexmediaserver-installer#14]
Hi Andreas,

Thanks for posting the PMS Raspberry Pi installer. After following your instructions I received an error trying to install on my RP2. Any suggestions? See below.

sudo apt-get install plexmediaserver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 plexmediaserver : Depends: libc6 (>= 2.19) but 2.13-38+rpi2+deb7u11 is to be installed
                   Depends: plexmediaserver-installer but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
jonathan@PI2B ~ $

**Comment by uglymagoo** [comment]
Hi @opentrail 

Please use a more recent Linux distribution, at least Debian 7.x (Jessie). Debian 6.0 (Wheezy) is not supported. Where did you get such an old Linux image in 2017? :)

Btw: My instructions tell you to install plexmediaserver-installer, not plexmediaserver.

Best regards
Jan
