### ISSUE TITLE
Scaleway arm64 issues

### ISSUE THREAD

**Issue by shadycuz** [uglymagoo/plexmediaserver-installer#15]
Hey,

I was hoping I could run your package on scaleway arm64 servers. I'm on ubuntu16.04. I used these instructions. https://www.dev2day.de/typo3/projects/plex-media-server/

Service starts

```
root@scw-eedb38:~# service plexmediaserver status
● plexmediaserver.service - LSB: Plex Media Server
   Loaded: loaded (/etc/init.d/plexmediaserver; bad; vendor preset: enabled)
   Active: active (exited) since Sat 2017-07-08 16:59:01 UTC; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18684 ExecStop=/etc/init.d/plexmediaserver stop (code=exited, status=0/SUCCESS)
  Process: 18737 ExecStart=/etc/init.d/plexmediaserver start (code=exited, status=0/SUCCESS)

Jul 08 16:59:00 scw-eedb38 systemd[1]: Starting LSB: Plex Media Server...
Jul 08 16:59:00 scw-eedb38 su[18743]: Successful su for plex by root
Jul 08 16:59:00 scw-eedb38 su[18743]: + ??? root:plex
Jul 08 16:59:00 scw-eedb38 su[18743]: pam_unix(su:session): session opened for user plex by (uid=0)
Jul 08 16:59:01 scw-eedb38 plexmediaserver[18737]: Starting Plex Media Server: done
Jul 08 16:59:01 scw-eedb38 systemd[1]: Started LSB: Plex Media Server.
```

I don't see the port open...
```
root@scw-eedb38:~# netstat -atun
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0     36 10.10.33.43:22          192.220.125.128:38770   ESTABLISHED
tcp6       0      0 :::22                   :::*                    LISTEN
udp        0      0 0.0.0.0:68              0.0.0.0:*
udp        0      0 10.10.33.43:123         0.0.0.0:*
udp        0      0 127.0.0.1:123           0.0.0.0:*
udp        0      0 0.0.0.0:123             0.0.0.0:*
udp6       0      0 fe80::dc19:88ff:fe0:123 :::*
udp6       0      0 ::1:123                 :::*
udp6       0      0 :::123                  :::*
```

It didn't appear to install any plexmediaserver files, just the parent dir's.
```
root@scw-eedb38:~# ls /var/lib/plexmediaserver/Library/Application\ Support/
root@scw-eedb38:~#
```
Did I install the right thing?
```
root@scw-eedb38:~# apt-get install plexmediaserver-installer
Reading package lists... Done
Building dependency tree
Reading state information... Done
plexmediaserver-installer:armhf is already the newest version (1.7.5.4035-313f93718-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@scw-eedb38:~#
```

Let me know if I missed any other output you might need? 

Thanks,
Levi

**Comment by shadycuz** [comment]
I believe the post install is not firing.

**Comment by uglymagoo** [comment]
HI @shadycuz 
I had one user report his issue before ( https://github.com/uglymagoo/plexmediaserver-installer/issues/10#issuecomment-301223319 ) but the user was not interested in a solution ^^ I suppose their arm64 CPU is not compatible with the Netgear armv7 build of Plex. So with your help we could add a rule, to use the Synology build. However this also means you will not have any video transcoding capability within Plex. Moreover, I just [read](https://blog.simos.info/a-closer-look-at-the-new-arm64-scaleway-servers-and-lxd/) scaleway uses KVM to virtualize their arm64 platform, so I am not sure KVM supports armv7 instructions in an arm64 guest.

To debug this issue further please try to start "Plex Media Server" manually (see this [post](https://support.plex.tv/hc/en-us/articles/201242707-Plex-Media-Scanner-via-Command-Line) for instructions how the set LD_LIBRARY_PATH on Linux beforehand) and post the error.

Btw. the location of the installed binaries is /usr/lib/plexmediaserver :)

**Comment by shadycuz** [comment]
ahh no transcode? So directstream? hmmm I've had people say docker container? Is that a solution? 

Let me spin up another server and see what the errors are on starting.

Thanks for your time.

**Comment by uglymagoo** [comment]
docker would change nothing regarding the scaleway servers.

**Comment by shadycuz** [comment]
@uglymagoo scaleway also has an armv7, maybe I should try this.

I'm not sure how to start plex manually...

```
root@scw-6133eb:~# export LD_LIBRARY_PATH=/usr/lib/plexmediaserver

root@scw-6133eb:~# /usr/lib/plexmediaserver/Plex\ Media\ Scanner -r
-bash: /usr/lib/plexmediaserver/Plex Media Scanner: cannot execute binary file: Exec format error

root@scw-6133eb:~# /usr/lib/plexmediaserver/Plex\ Media\ Server
-bash: /usr/lib/plexmediaserver/Plex Media Server: cannot execute binary file: Exec format error

root@scw-6133eb:~# file /usr/lib/plexmediaserver/Plex\ Media\ Server
/usr/lib/plexmediaserver/Plex Media Server: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.16, stripped
```

Some what interesting? https://stackoverflow.com/questions/22460589/armv8-running-legacy-32-bit-applications-on-64-bit-os

More interesting https://forum.odroid.com/viewtopic.php?f=135&t=18806

**Comment by shadycuz** [comment]
Okay well looks like I close this =/  https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2544


> Problem: Scaleway ARM64 nodes use Cavium ThunderX CPU, which is an implementation of the ARM Ltd ARMv8 architecture that implements only the required AArch64 instructions set. Cavium did not implement the optional AArch32 instruction set, which includes backwards compatibility with ARMv5 through ARMv7 (the Pi2+ Raspbian runs ARMv6hf+ARMv7-fastpath 32-bit instructions).
> 
> The RPi makes use of 32-bit instructions, which the Cavium ThunderX SoC has no method to execute.
> 
> Result: We'll currently have to maintain use of the C1 nodes for building non-AArch64 ARM builds, as the ARM64 nodes are physically incapable of executing the binaries, outside of virtualization/QEMU.

**Comment by uglymagoo** [comment]
Thank you very much for this information. I suppose this will help many other users.

**Comment by shadycuz** [comment]
@uglymagoo No problem, I would say scaleway really shot themselves in the foot with that CPU. It really limits what those VM's can do.
