### ISSUE TITLE
can't open page in rpi3 after 1.9.1 update

### ISSUE THREAD

**Issue by zoro0rkd** [uglymagoo/plexmediaserver-installer#18]
$sudo service plexmediaserver status

● plexmediaserver.service - Plex Media Server for Linux
   Loaded: loaded (/lib/systemd/system/plexmediaserver.service; enabled)
  Drop-In: /etc/systemd/system/plexmediaserver.service.d
           └─override.conf
   Active: active (running) since 목 2017-09-21 17:17:08 KST; 3h 38min ago
 Main PID: 356 (sh)
   CGroup: /system.slice/plexmediaserver.service
           ├─356 /bin/sh -c LD_LIBRARY_PATH=/usr/lib/plexmediaserver "/usr/lib/plexmediaserver/Plex Media Server"
           └─368 /usr/lib/plexmediaserver/Plex Media Server

===
service is running but 32400 port is not open~
I don't know why~ I think 1.9.1 file has something wrong

**Comment by uglymagoo** [comment]
Please read the advice in [my post about the 1.9.1 update](http://forums.plex.tv/discussion/comment/1520509/#Comment_1520509).

**Comment by uglymagoo** [comment]
I fixed this problem in the last commit. Please follow [my guide](http://forums.plex.tv/discussion/comment/1521085/#Comment_1521085) to restore your system.

**Comment by zoro0rkd** [comment]
thanks~~
