### ISSUE TITLE
Attempted to build and install on stretch

### ISSUE THREAD

**Issue by vvallee** [uglymagoo/plexmediaserver-installer#19]
builds fine, after adding with dpkg installer seems to work.
However plex refuses to start:

``root@raspberrypi:/home/pi# ./plexmediaserver-installer/usr/sbin/start_pms
6 3000 /root/Library/Application Support
8192
Illegal instruction``

**Comment by uglymagoo** [comment]
Your device is not supported. I assume you try to use Plex on a Raspberry Pi 1 or Zero or something like that. You need an armv7 or armv8 device with aarch32 support.

**Comment by vvallee** [comment]
Yep that's it. Armv6 

Thanks anyhow!
