### ISSUE TITLE
Certificate expired for https://dev2day.de

### ISSUE THREAD

**Issue by kapgit** [uglymagoo/plexmediaserver-installer#21]
Hi,
Not sure whether I should create a new issue for a certificate expiry, but here it is:

Running on Raspberry PI 3, debian 7 (should not be relevant)

'apt-get update' is stopping with error code:

```
Err https://dev2day.de jessie/main armhf Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates                                     .crt CRLfile: none
```

Seems the website certificate for https://dev2day.de expired today 9 Oct 2017

**Comment by uglymagoo** [comment]
Thx for the info. It's fixed now :)
