### ISSUE TITLE
Any plans to release version >1.10.1.4602

### ISSUE THREAD

**Issue by m-ghaoui** [uglymagoo/plexmediaserver-installer#23]
Hi,

I've been using your repo for a while. Everything worked perfectly until the beginning of December (1.10.1.4602-f54242b6b-1) when the subtitles started disappearing on the Chromecast. 

https://forums.plex.tv/discussion/288806/plex-losing-subtitle-while-playing/p14

It seems that it is a known issue and there have been updates with potential fixes. Any plans to date the version in your repo?

Another question I had: Everything worked perfectly till 1.10. Is there a way to downgrade to an older version? 

Thanks!

**Comment by uglymagoo** [comment]
At the moment, 1.10.1.4602 is the most recent public and stable release. All newer releases are currently closed Beta Plex Pass releases [1]. For obvious reasons I will not push closed betas to my public repo or release the links here.

However, if you are Plex Pass user you can always download the Betas from my thread in the Plex forum [2].

Moreover, Debian / Ubuntu cache the old packages in `/var/cache/apt/archives/`. There you will find 1.9.x if you had it previously installed.

[1] https://forums.plex.tv/discussion/62832/plex-media-server#latest
[2] https://forums.plex.tv/discussion/221444/unofficial-armhf-arm64-multiarch-debian-package-e-g-rpi-2-3-bpi-odroid#latest
