### ISSUE TITLE
Banned from your repository

### ISSUE THREAD

**Issue by dalgwen** [uglymagoo/plexmediaserver-installer#24]
Hello,

First, sorry to bother you.
I think I clicked too fast when exploring manually (with my browser) your repository, and my IP may have been banned. I must be a real fast clicker :)
Could you please unbanned me ?  It was today, maybe near 14h UTC (I don't feel like to put my IP on internet, maybe if you need it, we can use some DM on twitter (@dalgwen) ?)

Second, for the inconvenience caused (time is precious), I would like to make a small donation, do you use something other than bitcoin ?

Thanks !

**Comment by uglymagoo** [comment]
> Could you please unbanned me ? It was today, maybe near 14h UTC

My fail2ban rules might be a little too extreme :) I think I found you. Please try again.

> I would like to make a small donation, do you use something other than bitcoin

My email jft@dev2day.de is also a paypal account ;) But don't worry, it was no problem at all.

**Comment by dalgwen** [comment]
Wow, that was fast 👍 
I send you a little paypal donation anyway, to thank you for your work.
