### ISSUE TITLE
Plex Media Server doesn't get found on the Plex app

### ISSUE THREAD

**Issue by asteriskUser** [uglymagoo/plexmediaserver-installer#25]
Hi All,

I'm running the PMS on a armhf7 platfrom inside a docker container using a vanilla raspbian strech image. I already got the server up and running. Unfortunately the server itself dosn't get found on the plex media app, as shown in the figure below:

![grafik](https://user-images.githubusercontent.com/28922259/37357622-d437b0a2-26e0-11e8-9754-adf437d13653.png)

I suppose that the plex app is a part of the PMS and is running independent of the actual server. The following processes are currently up and running:

> 

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1   4484  2272 ?        Ss   16:32   0:00 /bin/bash /entry_point.sh
root         8  0.0  0.1   4640  2536 pts/0    Ss   16:32   0:00 bash
plex      1100  0.0  0.0   1432   412 ?        S    17:00   0:00 /bin/sh /usr/sbin/start_pms
plex      1102  0.5  2.2 235900 45928 ?        Sl   17:00   0:02 ./Plex Media Server
plex      1113  2.0  1.5 197008 31876 ?        SNl  17:00   0:10 Plex Plug-in [com.plexapp.system] /usr/lib/plexmediaserver/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-version
plex      1161  0.1  0.7 167904 14708 ?        Sl   17:00   0:00 /usr/lib/plexmediaserver/Plex DLNA Server
plex      1163  0.0  0.6 114724 12308 ?        Sl   17:00   0:00 /usr/lib/plexmediaserver/Plex Tuner Service /usr/lib/plexmediaserver/Resources/Tuner/Private /usr/lib/plexmediaserver/Resources/Tuner/Shared 1.12.0.4829-6de959918 32600 /wa
plex      1200  1.4  1.4 134952 29332 ?        Sl   17:00   0:06 Plex Plug-in [com.plexapp.agents.imdb] /usr/lib/plexmediaserver/Resources/Plug-ins-6de959918/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py --server-ver

> 

As the server is running within the same container as the app I don't really understand the problem here.

**Comment by uglymagoo** [comment]
I see, I forgot to mention this step in my installation guide. You first have to access the web frontend from an IP that's in the same subnet as your server. So with your docker setup, make sure to temporary use bridge networking and than complete the step "On a Different Network" from the official guide: https://support.plex.tv/articles/200288586-installation/

But please be aware, that questions like this are best asked in our support forum: https://forums.plex.tv/categories/pms-raspberry-pi
