### ISSUE TITLE
Install fails on the Libre Renegade Arm64 board.

### ISSUE THREAD

**Issue by slloyd88** [uglymagoo/plexmediaserver-installer#29]
I have tried several different debian images but all fail to install plexmediaserver.  The board is a Libre Renegade (https://libre.computer/products/boards/roc-rk3328-cc/).   I followed your instructions for installing on ARM64 and get the following:

root@renegade:/var/www/tmp# apt-get install plexmediaserver-installer:armhf
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  gcc-6-base:armhf libc6:armhf libgcc1:armhf
Suggested packages:
  glibc-doc:armhf locales:armhf
The following NEW packages will be installed:
  gcc-6-base:armhf libc6:armhf libgcc1:armhf plexmediaserver-installer:armhf
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,566 kB of archives.
After this operation, 8,948 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main armhf gcc-6-base armhf 6.3.0-18+deb9u1 [180 kB]
Get:4 https://dev2day.de/pms stretch/main armhf plexmediaserver-installer armhf 1.13.5.5332-21ab172de-1 [7,658 B]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main armhf libgcc1 armhf 1:6.3.0-18+deb9u1 [38.5 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch/main armhf libc6 armhf 2.24-11+deb9u3 [2,340 kB]
Fetched 2,566 kB in 2s (1,205 kB/s)
Preconfiguring packages ...
Selecting previously unselected package gcc-6-base:armhf.
(Reading database ... 48254 files and directories currently installed.)
Preparing to unpack .../gcc-6-base_6.3.0-18+deb9u1_armhf.deb ...
Unpacking gcc-6-base:armhf (6.3.0-18+deb9u1) ...
Selecting previously unselected package libgcc1:armhf.
Preparing to unpack .../libgcc1_1%3a6.3.0-18+deb9u1_armhf.deb ...
Unpacking libgcc1:armhf (1:6.3.0-18+deb9u1) ...
Selecting previously unselected package libc6:armhf.
Preparing to unpack .../libc6_2.24-11+deb9u3_armhf.deb ...
Unpacking libc6:armhf (2.24-11+deb9u3) ...
Selecting previously unselected package plexmediaserver-installer:armhf.
Preparing to unpack .../plexmediaserver-installer_1.13.5.5332-21ab172de-1_armhf.deb ...
Unpacking plexmediaserver-installer:armhf (1.13.5.5332-21ab172de-1) ...
Setting up gcc-6-base:armhf (6.3.0-18+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u4) ...
Setting up libgcc1:armhf (1:6.3.0-18+deb9u1) ...
Setting up libc6:armhf (2.24-11+deb9u3) ...
Setting up plexmediaserver-installer:armhf (1.13.5.5332-21ab172de-1) ...
Adding user plex to group video
Downloading readynas package ...
######################################################################## 100.0%
Passed checksum test.
Extracting readynas.deb ...
rm: cannot remove '/etc/systemd/system/plexmediaserver.service.d/override.conf': No such file or directory
Synchronizing state of plexmediaserver.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable plexmediaserver
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f88c80730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f88c80730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Comment by uglymagoo** [comment]
It's a bug in your rockchip Debian distribution, not in this package. Please read e.g. 

https://github.com/ayufan-rock64/linux-build/issues/136

**Comment by slloyd88** [comment]
I see now. Thank you!
