### ISSUE TITLE
Think problem with Path in plexmediaserver in defaut

### ISSUE THREAD

**Issue by BipBip1981** [uglymagoo/plexmediaserver-installer#3]
Hi,

I think you miss or do mistake on path in /etc/default/plexmediaserver because DLNA server not work, i have this error same time in Log, when i tune path, Plex created new directory in /var/lib/plexmediaserver and all will be good...

Sorry for my poor english

Jan 04, 2017 11:59:54.467 [0x6f1ff410] DEBUG - Mapped client to profile Panasonic Viera 3D TV using header User-Agent: Panasonic MIL DLNA CP UPnP/1.0 DLNADOC/1.50
Jan 04, 2017 11:59:54.468 [0x6f1ff410] DEBUG - Mapped object ed8796b474d949c54ece to /library/sections/2/all part 0 on server http://127.0.0.1:32400/
Jan 04, 2017 11:59:54.470 [0x6f1ff410] DEBUG - Downloading document http://127.0.0.1:32400/library/sections/2/all
Jan 04, 2017 11:59:54.470 [0x6f1ff410] DEBUG - HTTP requesting GET http://127.0.0.1:32400/library/sections/2/all
Jan 04, 2017 11:59:54.822 [0x6f1ff410] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/library/sections/2/all
Jan 04, 2017 11:59:54.849 [0x6f1ff410] DEBUG - Caching document http://127.0.0.1:32400/library/sections/2/all as 89dd04a675e4a6bba9740e1a1c4edb189fe126a8
Jan 04, 2017 11:59:54.874 [0x6f1ff410] DEBUG - Downloading document http://127.0.0.1:32400/library/metadata/1,2,3,4,5,6,7,8,11,12,13,71,14,16,30,17,18,19,72,21,25,22,24,23,26,42,27,28,29,31,32,33,34,35,36,37,73,38,39,40,41,46,15,47,44,45,48,49,50,51,52,53,54,55,56,57,20,58,59,60,61,63,74,62,43,64,65,66,67,68,69,70,77,78,79,75,80,76,81,82,83,84,85
Jan 04, 2017 11:59:54.874 [0x6f1ff410] DEBUG - HTTP requesting GET http://127.0.0.1:32400/library/metadata/1,2,3,4,5,6,7,8,11,12,13,71,14,16,30,17,18,19,72,21,25,22,24,23,26,42,27,28,29,31,32,33,34,35,36,37,73,38,39,40,41,46,15,47,44,45,48,49,50,51,52,53,54,55,56,57,20,58,59,60,61,63,74,62,43,64,65,66,67,68,69,70,77,78,79,75,80,76,81,82,83,84,85
Jan 04, 2017 12:00:54.946 [0x6f1ff410] ERROR - Error issuing curl_easy_perform(handle): 28
Jan 04, 2017 12:00:54.946 [0x6f1ff410] DEBUG - HTTP simulating 408 after curl timeout
Jan 04, 2017 12:00:54.947 [0x6f1ff410] ERROR - HTTP 408 downloading url http://127.0.0.1:32400/library/metadata/1,2,3,4,5,6,7,8,11,12,13,71,14,16,30,17,18,19,72,21,25,22,24,23,26,42,27,28,29,31,32,33,34,35,36,37,73,38,39,40,41,46,15,47,44,45,48,49,50,51,52,53,54,55,56,57,20,58,59,60,61,63,74,62,43,64,65,66,67,68,69,70,77,78,79,75,80,76,81,82,83,84,85
Jan 04, 2017 12:00:54.947 [0x6f1ff410] ERROR - GetStreamMetadata - unable to get directory /library/metadata/1,2,3,4,5,6,7,8,11,12,13,71,14,16,30,17,18,19,72,21,25,22,24,23,26,42,27,28,29,31,32,33,34,35,36,37,73,38,39,40,41,46,15,47,44,45,48,49,50,51,52,53,54,55,56,57,20,58,59,60,61,63,74,62,43,64,65,66,67,68,69,70,77,78,79,75,80,76,81,82,83,84,85

**Comment by uglymagoo** [comment]
What path did you set exactly? Typically, Plex uses the home directory of the user running the Plex Media Server (default: user plex with home /var/lib/plexmediaserver). So /etc/default/plexmediaserver is nearly empty or commented out in the default installation and no extra path is required. Did you change the user?

**Comment by BipBip1981** [comment]
I try more test because now DLNA work just after fresh install and share only a test directory with 1 files in... and metadata is find... maybe Plex is bug or my configuration/directory/network have problem... sorry

**Comment by BipBip1981** [comment]
..the problem see to comme from my movies directory.....

**Comment by uglymagoo** [comment]
Good luck fixing your problem :)
