### ISSUE TITLE
Ubuntu 16.04 / 18.04 support

### ISSUE THREAD

**Issue by dutch2005** [uglymagoo/plexmediaserver-installer#30]
Thanks for the awesome tutorial.

Any chance you could also add support for ubuntu? e.g. 16.04 and/or 18.04 ? (the LTS versions)

Imo to start the files and folders from "stretch" to "xenial" and "bionic" should suffice 

thnx!

**Comment by uglymagoo** [comment]
Ubuntu is supported. Just use the stretch repo as it is.
