### ISSUE TITLE
more detailed installation steps

### ISSUE THREAD

**Issue by dutch2005** [uglymagoo/plexmediaserver-installer#31]
Hi,

So me again :-)

At the installation steps you state "the nas package"

[removed link to private Beta]

This one is "armv7"

I've got a cloud ARM64 server running at scaleway - https://www.scaleway.com/baremetal-cloud-servers/

I can unpack the rbw file

see: https://imgur.com/a/sjhuomj (it has the plexmediaserver files).

What to do next?

**Comment by uglymagoo** [comment]
Don't get me wrong, but this is not an issue. Please use the Plex forum for this kind of support. https://forums.plex.tv/tags/c/third-party/apps-tools/server-raspberry-pi

Just some important infos here:
(1) Don't use the betas. The public package in my repo is much more stable than the beta you have linked to.
(2) Please remove the link from your above message! It's still a closed Plex Pass Beta. Don't post those links publicly.
(3) You cannot use the armv7 packages on the arm64 scaleway servers. They do not support AARCH32 and the binaries will not run. Please wait for the public arm64 release. I cannot distribute a Debian / Ubuntu arm64 package nor give you instructions how to prepare the arm64 Alpha packages for Ubuntu arm64 till it's out of Alpha.
(4) Read the following package script to get an idea which NAS packages I am talking about: https://github.com/uglymagoo/plexmediaserver-installer/blob/master/DEBIAN/postinst
