### ISSUE TITLE
PMS 1.15.8.1198 has been released

### ISSUE THREAD

**Issue by RandomSamurai** [uglymagoo/plexmediaserver-installer#33]
It has some fixes,  but most importantly is has the fix that 'Certain clients (third party Samsung and OpenPHT) would fail to resume video'  that was broken in 1.15.3.876.

can this be updated?

**Comment by uglymagoo** [comment]
Just migrate to the official package. The last few package updates already told you to do so, but the migration instructions are still available at the end of the following Plex thread:

https://forums.plex.tv/t/read-me-first-about-server-armv7-and-armv8-ubuntu-debian/226567
