### ISSUE TITLE
what does it mean to repack something?

### ISSUE THREAD

**Issue by lattice0** [uglymagoo/plexmediaserver-installer#4]
Could you please tell me what is repackaging and how you did that? I'm intersted in learning. At least the keywords to search would help.

**Comment by uglymagoo** [comment]
Hi Lucas,
in a nutshell, it's just the progress of migrating a software package designed for one package manager / system to another. You have to know both package formats and Linux quite well. A good start is the Debian packaging guide: https://wiki.debian.org/Packaging .

**Comment by lattice0** [comment]
Thank you, I began reading it after I found your repackaging. It seems like you took the arm package for one of these NATs and packaged it to debian, right? Can I extract the binaries and just install? Just for learning, you know.

**Comment by uglymagoo** [comment]
Of course. My installer uses the ARM 6.x RN2xx Netgear package from plex.tv. Just take a look at my DEBIAN/postinst bash script. It contains the code to extract the binaries. However, you also need some LD_LIBRARY_PATH hacks. usr/sbin/start_pms is all the code you need to start the binaries.
