### ISSUE TITLE
Uninstallable dependency - libc6:armhf

### ISSUE THREAD

**Issue by russellseymour** [uglymagoo/plexmediaserver-installer#6]
I am using your repo again to rebuild my ODROID C2 computer as the SDCard was corrupt and it would not start up properly.  You have my thanks for setting this up as it makes life _so_ much easier :).

I have gone through the steps of adding your repo and it does attempt to install `plexmediaserver-installer:armhf`, however I get the following error:

```
plexmediaserver-installer:armhf : Depends: libc6:armhf (>= 2.19) which is a virtual package and is not provided by any available package
```

I have searched for `libc6:armhf` and it is not available (as the message suggests).  I had thought that I might be able to resolve the dependency using `libc6-armel-armhf-cross` but that did not work.

I am using `Ubuntu 16.04.1 LTS` on an ODROID C2 device.  The kernel in use is:

```
Linux media-1 3.14.65-73 #1 SMP PREEMPT Tue Aug 2 08:21:02 BRT 2016 aarch64 aarch64 aarch64 GNU/Linux
```

The version of `libc6` according to `ldd --version` is:

```
ldd (Ubuntu GLIBC 2.23-0ubuntu3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Do you have any pointers on how I could fix this please?  As mentioned this worked very well before.  Thanks lots.

**Comment by uglymagoo** [comment]
Your enabled Ubuntu repositories do not provide packages for the armhf architecture, only for arm64 I assume. The armhf repository is required, as there is no arm64 build available of PMS at the moment. So please check your local /etc/apt/sources.list and /etc/apt/sources.list.d/ entries, as the official Ubuntu repositories provide libc6 for armhf [1]. Please first check if hardkernel provides a armhf repository. Worst case scenario, use the upstream Ubuntu repository in your /etc/apt/sources.list [2].

[1] http://packages.ubuntu.com/xenial/libc6
[2] deb [armhf] http://archive.ubuntu.com/ubuntu xenial main

**Comment by danoe** [comment]
I just installed plexmediaserver on odroid c2 and fresh installed Ubuntu, I just followed the instructions from the [website](https://www.dev2day.de/typo3/projects/plex-media-server/) and it worked without any problems.

`root@odroid64# dpkg --add-architecture armhf`

```
root@odroid64# aptitude install plexmediaserver-installer:armhf
The following NEW packages will be installed:
  curl{a} gcc-6-base:armhf{a} libc6:armhf{a} libgcc1:armhf{a} plexmediaserver-installer:armhf
0 packages upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,338 kB of archives. After unpacking 9,131 kB will be used.
Do you want to continue? [Y/n/?]
Get: 1 http://ports.ubuntu.com/ubuntu-ports xenial/main armhf gcc-6-base armhf 6.0.1-0ubuntu1 [14.4 kB]
Get: 2 http://ports.ubuntu.com/ubuntu-ports xenial/main armhf libgcc1 armhf 1:6.0.1-0ubuntu1 [38.6 kB]
Get: 3 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf libc6 armhf 2.23-0ubuntu5 [2,148 kB]
Get: 4 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 curl arm64 7.47.0-1ubuntu2.2 [133 kB]
Get: 5 https://dev2day.de/pms jessie/main armhf plexmediaserver-installer armhf 1.3.4.3285-b46e0ea-1~jessie [4,056 B]
Fetched 2,338 kB in 1s (1,782 kB/s)
```

My sources lists
```
root@odroid64# cat /etc/apt/sources.list
deb http://ports.ubuntu.com/ubuntu-ports/ xenial main universe restricted multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial main universe restricted multiverse

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main universe restricted multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main universe restricted multiverse

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted universe multiverse

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted universe multiverse

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-proposed main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-proposed main restricted universe multiverse
```
```
root@odroid64# cat /etc/apt/sources.list.d/odroid.list
deb http://deb.odroid.in/c2/ xenial main
root@odroid64# cat /etc/apt/sources.list.d/pms.list
deb https://dev2day.de/pms/ jessie main
root@odroid64# cat /etc/apt/sources.list.d/saiarcot895-ubuntu-myppa-xenial.list
deb http://ppa.launchpad.net/saiarcot895/myppa/ubuntu xenial main
# deb-src http://ppa.launchpad.net/saiarcot895/myppa/ubuntu xenial main
```

**Comment by uglymagoo** [comment]
No more feedback, so issue closed as far as I know.
