### ISSUE TITLE
AMD Seattle does not support the Netgear binary

### ISSUE THREAD

**Issue by trini** [uglymagoo/plexmediaserver-installer#7]
The postinst script currently picks the 'armel' package to use on ARMv8 architecture.  This isn't the best choice as armel means using soft-float and these instructions are optional and not likely to exist on ARMv8 cores.  Instead on ARMv8 we want to use the armhf package, ie "synology".  I've confirmed the breakage and the fix on my Overdrive 1000 (AMD Seattle) based system.

**Comment by uglymagoo** [comment]
@trini Correct argument, wrong conclusion. The netgear readynas package is just wrongly named. It is the best native ARMv7 binary out there and the only one with enabled video transcoding. Just compare the binaries of both releases and their ELF architecture-specific information.

**Comment by trini** [comment]
The problem is that on ARMv8 you're installing non-functional binaries for the hardware.  To be clear, the "netgear" binaries do not run and the "synology" ones do, at least on AMD Seattle platforms.  If you're seeing them work on other ARMv8 platforms then we need to update the logic a bit more to check for ARMv8 and some other features.

**Comment by uglymagoo** [comment]
Yes, your system is the first ARMv8 system that has problems with the netgear build. So first we have to find the reasons for that. Please post  details: Linux distribution, 32 oder 64 bit mode, /proc/cpuinfo, crash dump of the Plex Transcoder (do you know how to configure LD_LIBRARY_PATH to include the plex bundled libs?), dmesg output, ...

**Comment by uglymagoo** [comment]
Yes, your system is the first ARMv8 system that has problems with the netgear build. So first we have to find the reasons for that. Please post  details: Linux distribution, 32 oder 64 bit mode, /proc/cpuinfo, crash dump of the Plex Transponder (do you know how to configure LD_LIBRARY_PATH to include the plex bundled libs), dmesg output, ...

**Comment by trini** [comment]
I'm running this under docker, so I think https://github.com/linuxserver/docker-plex/blob/master/Dockerfile provides the most useful background wrt distribution.  The host is in 64bit mode (openSUSE Leap 42.2) and /proc/cpuinfo starts with:
> processor       : 0
> BogoMIPS        : 500.00
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x1
> CPU part        : 0xd07
> CPU revision    : 2

And it's not the transcoder that's failing, we don't get that far:

> Server startup complete. Host name is XXXXX. Local service cookie is 123....
> 6 3000 /config/Library/Application Support
> 8192
> Segmentation fault
... repeats over and over ...

**Comment by uglymagoo** [comment]
Just a segmentation fault, no illegal instructions error. So it's just a normal bug triggered by your setup, I assume. Please be more specific about your docker setup. I was not aware there was a working plex arm docker image and the above docker file is only for amd64.

**Comment by trini** [comment]
re Docker, yes, there's a multitude of setups (almost all of which use your repository to do the hard work wrt plex).  And yes, sorry, I gave you the wrong link before.  I meant https://github.com/linuxserver/docker-plex-armhf

**Comment by uglymagoo** [comment]
Are you sure it's a good idea to use an ARMv7 32 bit container in an ARMv8 64 bit docker setup? It would be great if you could try the netgear build without docker (maybe in an Debian / Ubuntu Live System?) just to make sure to the netgear build is really incompatible with your AMD system and not just with your docker setup

**Comment by trini** [comment]
Yes, doing 32bit mode is just as supported on ARMv8 as it is with x86_64/x86 and 32bit containers on 64bit hosts doesn't add any real complexity here.  And yes, I have taken Docker out of the equation and thrown the rootfs + plex into a directory, chroot'd and found the same problem.

**Comment by trini** [comment]
@uglymagoo OK, so I did a bit more hard poking and you can do:
`VEND=$(cat /sys/devices/virtual/dmi/id/board_vendor 2>/dev/null)`
`MODEL=$(cat /sys/devices/virtual/dmi/id/board_name 2>/dev/null)`
and check for "AMD" and "Seattle" to determine we're here, rather than say dragonboard (I fired mine up, there are no usable differences in /proc/cpuinfo and then VEND/MODEL are empty).

**Comment by uglymagoo** [comment]
@trini As I mentioned above, it appears to be just a Plex Media Server bug. I would like to find the real reason for the crash before I disable video transcoding for AMD Seattle altogether. The above logs are from docker, right? Could you please post the normal Plex logs (e.g. Plex Media Server.log)? Please see [plex doc 1](https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files) and [plex doc 2](https://support.plex.tv/hc/en-us/articles/201455336-Crash-Logs-Plex-Media-Server). Also a crash dump would be great to give the Plex guys the chance to find the error.

Please also take a look at the kernel log (e.g. dmesg).

I also came across posts that suggest AArch32 rootfs running on an AArch64 kernel are just not supported by some distros (e.g. [Fedora](https://lists.fedoraproject.org/archives/list/arm@lists.fedoraproject.org/thread/D7MLYMDVNNXKRY5X6JLRYK7VL2XHOLUN/)) and this operation might cause problems. Please also take a look at the suggested kernel options. So it would really be great if you could try the Netgear build in 64 bit Debian / Ubuntu running on bare metal.

**Comment by uglymagoo** [comment]
The thing is, the Netgear build is the build most users should use and it might work on your hardware in other setups. So please consider this solution: the installer checks if /etc/plexmediaserver/forcesynology exists and always uses the Synology build then. You can easily change the linuxserver.io Docker file to add that file.

**Comment by uglymagoo** [comment]
#8

**Comment by trini** [comment]
@uglymagoo as to compatibility, yes, you have to have CONFIG_COMPAT enabled in your kernel (and in turn 4K pages) and CentOS (and Fedora I assume) currently default to 64K pages and no 32bit compat.  openSUSE/Debian (and others) don't have that problem as if they did nothing 32bit would work (I did a 32bit static hello world on all 3, CentOS fails, everyone else is fine).

I'll save off another container to get the logs for you with and we can move from there.  But I would like to see your package handle this correctly as I only got the hint to try synology instead due to someone else hitting this problem, figuring out this work-around, and promising to write up something more, a month+ ago :)

**Comment by uglymagoo** [comment]
@trini The logs are stored in the first mount volume (/config).

**Comment by uglymagoo** [comment]
@trini Most likely unrelated, just to make sure: have you seen this [issue](https://github.com/linuxserver/docker-plex/issues/71)? Are you sure your /config mounted volume has the exec mount option set? It would explain your issue, because the Synology build does not retrieve codecs as the transcoder is disabled in this release.

Edit: I am quite sure that's your problem :)

**Comment by trini** [comment]
It's not that issue.  Here's the first log:
# docker start -ai plex-segfault 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing... 
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
Found user 'avahi' (UID 106) and group 'avahi' (GID 107).
Successfully dropped root privileges.
avahi-daemon 0.6.32-rc starting up.
No service file found in /etc/avahi/services.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface veth0....IPv6 with address fe80::....
New relevant interface veth0....IPv6 for mDNS.
Joining mDNS multicast group on interface docker0.IPv6 with address fe80::....
New relevant interface docker0.IPv6 for mDNS.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv6 with address fe80::.....
New relevant interface eth0.IPv6 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.196.
New relevant interface eth0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::... on veth0....*.
Registering new address record for fe80::... on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::... on eth0.*.
Registering new address record for 192.168.0.196 on eth0.IPv4.
Server startup complete. Host name is opus.local. Local service cookie is ....
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
6 3000 /config/Library/Application Support
8192
Segmentation fault
^CGot SIGTERM, quitting.
Leaving mDNS multicast group on interface veth0dd1e68.IPv6 with address fe80::....
Leaving mDNS multicast group on interface docker0.IPv6 with address fe80::....
Leaving mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::....
Leaving mDNS multicast group on interface eth0.IPv4 with address 192.168.0.196.
avahi-daemon 0.6.32-rc exiting.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by trini** [comment]
None of the other logs are ever created:
$ ls -R Library/
Library/:
Application Support

Library/Application Support:
$

**Comment by uglymagoo** [comment]
@trini Ok. So you believe PR #9 would fix the issue for now?

**Comment by uglymagoo** [comment]
@trini Do you use an AMD developer board from 2014? I have not found any other AMD ARM board in the market.

**Comment by trini** [comment]
@uglymagoo No, I have https://softiron.com/products/overdrive-1000/ which is shipping now.  And yes, #9 looks good but I only hesitate in that the next generation SoC might not have this issue.

**Comment by uglymagoo** [comment]
@trini We will see if there is any next generation AMD ARM product ^^ I am sure we will have a native ARM64 Plex server then.

I will merge PR #9 and the fix will be included in the next stable release. It should appear soon, as there are so many issues with 1.4.3 right now.
